# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LVPrevalidation
                                 A QGIS plugin
 This plugin assists the client to identify errors in the network and rectify them
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-06-22
        copyright            : (C) 2022 by waleed
        email                : waleedk745@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LVPrevalidation class from file LVPrevalidation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .lv_prevalidation import LVPrevalidation
    return LVPrevalidation(iface)
